services:
  liar-back:
    build: .
    container_name: liar-back
    restart: always
    env_file:
      - .env
    ports:
      - '127.0.0.1:5001:5001'
    networks:
      - app-network

networks:
  app-network:
    external: true
